name: Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.3"

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...

      - name: Run race detector
        run: go test -race -v ./...

      - name: Check code coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
